// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1:string):Promise<string>;

export function GetAIConfig():Promise<string>;

export function SavePredefinedFunctions(arg1:string):Promise<string>;

export function SetAIConfig(arg1:string):Promise<void>;
