// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1) {
  return window['go']['main']['App']['AIChat'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function LoadPredefinedFunctions() {
  return window['go']['main']['App']['LoadPredefinedFunctions']();
}

export function SavePredefinedFunctions(arg1) {
  return window['go']['main']['App']['SavePredefinedFunctions'](arg1);
}

export function SetAIConfig(arg1) {
  return window['go']['main']['App']['SetAIConfig'](arg1);
}
