// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AIChat(arg1:string):Promise<string>;

export function GetAIConfig():Promise<string>;

export function LoadPredefinedFunctions():Promise<string>;

export function P2PAddrs():Promise<Array<string>>;

export function P2PAnnounce(arg1:string):Promise<void>;

export function P2PConnIP(arg1:string):Promise<string>;

export function P2PConnKind(arg1:string):Promise<string>;

export function P2PConnect(arg1:string,arg2:number):Promise<void>;

export function P2PFindProviders(arg1:string,arg2:number):Promise<Array<main.P2PProvider>>;

export function P2PFullAddrs():Promise<Array<string>>;

export function P2PID():Promise<string>;

export function P2POpenStream(arg1:string,arg2:number):Promise<string>;

export function P2PPeers():Promise<Array<string>>;

export function P2PRoutingTableSize():Promise<number>;

export function P2PStart():Promise<string>;

export function P2PStop():Promise<void>;

export function P2PStopAnnounce(arg1:string):Promise<void>;

export function P2PStreamClose(arg1:string):Promise<void>;

export function P2PStreamCloseWrite(arg1:string):Promise<void>;

export function P2PStreamRead(arg1:string,arg2:number,arg3:number):Promise<main.P2PChunk>;

export function P2PStreamWrite(arg1:string,arg2:string):Promise<void>;

export function SavePredefinedFunctions(arg1:string):Promise<string>;

export function SetAIConfig(arg1:string):Promise<void>;
